name: Get YouTube Live m3u8

on:
  schedule:
    - cron: "0 */1 * * *"  # 每小时触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Generate .m3u8 files into ch/ from channels.txt
      run: |
        mkdir -p ch

        generate() {
          name="$1"
          url="$2"
          echo "#EXTM3U" > "ch/$name.m3u8"
          echo "#EXT-X-VERSION:3" >> "ch/$name.m3u8"
          echo "#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000" >> "ch/$name.m3u8"
          echo "$(yt-dlp -g "$url")" >> "ch/$name.m3u8"
        }

        while IFS="|" read -r name url; do
          if [[ -n "$name" && -n "$url" ]]; then
            generate "$name" "$url"
          fi
        done < channels.txt

    - name: Upload .m3u8 files as artifact
      uses: actions/upload-artifact@v4
      with:
        name: YTlive m3u8
        path: ch/*.m3u8

    - name: Push .m3u8 files to main branch under ch/
      run: |
        git config --global user.name "GOH3124"
        git config --global user.email "gohhh40163@github.com"
        git add ch/*.m3u8
        git commit -m "Update .m3u8 files in ch/ from workflow" || echo "No changes to commit"
        git push origin main
